parameters:
    #foo: bar

services:
    blade_tester_calendar.forms.event:
        class: "%blade_tester_calendar.form.type.event.class%"
        arguments: ["%blade_tester_calendar.classes.event.entity%"]

    blade_tester_calendar.forms.category:
        class: "%blade_tester_calendar.form.type.category.class%"
        arguments: ["%blade_tester_calendar.classes.category.entity%"]

    blade_tester_calendar.calendar:
        class: "BladeTester\CalendarBundle\Model\Calendar"
        arguments: ["@doctrine.orm.entity_manager", "%blade_tester_calendar.classes.event.entity%"]

    blade_tester_calendar.event_category_manager:
        class: "BladeTester\CalendarBundle\Model\EventCategoryManager"
        arguments: ["@doctrine.orm.entity_manager", "%blade_tester_calendar.classes.category.entity%"]